# Generated by Django 5.0.2 on 2024-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singername', models.CharField(max_length=30)),
                ('sage', models.IntegerField()),
                ('slocation', models.CharField(max_length=100)),
                ('semail', models.EmailField(max_length=254)),
                ('scontact', models.IntegerField()),
                ('songname', models.CharField(max_length=120)),
            ],
        ),
    ]
