# Generated by Django 5.0.2 on 2024-03-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=70)),
                ('cname', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
