# Generated by Django 5.0.2 on 2024-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empmodel',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empmodel',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
