# Generated by Django 5.0.2 on 2024-05-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SadiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=20)),
            ],
        ),
    ]
