# Generated by Django 5.0.2 on 2024-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=120)),
                ('roll', models.IntegerField(max_length=10)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
    ]
