# Generated by Django 4.1.4 on 2023-09-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_student_age_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='add',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
