# Generated by Django 4.1.4 on 2023-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_student_add_alter_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(null=True),
        ),
    ]
