# Generated by Django 5.1 on 2025-02-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nareshit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teachername', models.CharField(max_length=40)),
                ('teachersalary', models.IntegerField()),
                ('subject', models.CharField(max_length=40)),
            ],
        ),
    ]
